### ISSUE TITLE
Revisar los nombre de los escenarios

### ISSUE THREAD

**Issue by evolentini** [carlosdomenje/bdd_tp3_cdomenje#1]
Cada escenario debería tener una descripción que lo identifique en forma única.

https://github.com/carlosdomenje/bdd_tp3_cdomenje/blob/52d0100ec8e20703bf83043bfb76da0abac1e709/features/gestion.feature#L27

https://github.com/carlosdomenje/bdd_tp3_cdomenje/blob/52d0100ec8e20703bf83043bfb76da0abac1e709/features/gestion.feature#L34

https://github.com/carlosdomenje/bdd_tp3_cdomenje/blob/52d0100ec8e20703bf83043bfb76da0abac1e709/features/gestion.feature#L41

https://github.com/carlosdomenje/bdd_tp3_cdomenje/blob/52d0100ec8e20703bf83043bfb76da0abac1e709/features/busqueda.feature#L31

https://github.com/carlosdomenje/bdd_tp3_cdomenje/blob/52d0100ec8e20703bf83043bfb76da0abac1e709/features/busqueda.feature#L42

**Comment by carlosdomenje** [comment]
> Cada escenario debería tener una descripción que lo identifique en forma única.
> 
> https://github.com/carlosdomenje/bdd_tp3_cdomenje/blob/52d0100ec8e20703bf83043bfb76da0abac1e709/features/gestion.feature#L27
> 
> https://github.com/carlosdomenje/bdd_tp3_cdomenje/blob/52d0100ec8e20703bf83043bfb76da0abac1e709/features/gestion.feature#L34
> 
> https://github.com/carlosdomenje/bdd_tp3_cdomenje/blob/52d0100ec8e20703bf83043bfb76da0abac1e709/features/gestion.feature#L41
> 
> https://github.com/carlosdomenje/bdd_tp3_cdomenje/blob/52d0100ec8e20703bf83043bfb76da0abac1e709/features/busqueda.feature#L31
> 
> https://github.com/carlosdomenje/bdd_tp3_cdomenje/blob/52d0100ec8e20703bf83043bfb76da0abac1e709/features/busqueda.feature#L42

Tenia mal asociado el concepto de los Escenarios, pensaba que tenia que respetar el encabezado de cada requisito del test. Se modificaron varios errores de este tipo.
