### ISSUE TITLE
En la lista los elementos no se agregan ni al principio ni al final

### ISSUE THREAD

**Issue by evolentini** [carlosdomenje/bdd_tp3_cdomenje#2]
La lista como tal no tiene un requisito de orden y por lo tanto no tiene sentido agregar elementos al principio o al final, simplemente se agregan. Lo que debe estar ordenado es la lista de claves que se recupera con un método en particular

https://github.com/carlosdomenje/bdd_tp3_cdomenje/blob/52d0100ec8e20703bf83043bfb76da0abac1e709/features/busqueda.feature#L39

https://github.com/carlosdomenje/bdd_tp3_cdomenje/blob/52d0100ec8e20703bf83043bfb76da0abac1e709/features/busqueda.feature#L50

**Comment by carlosdomenje** [comment]
Perfecto Esteban, modifique el test para que directamente al ingresar un elemento a la lista, devuelva la lista de CLAVES ordenada alfabeticamente. En el ultimo commit esta la correccion
