### ISSUE TITLE
Mejorar la redacción del paso

### ISSUE THREAD

**Issue by evolentini** [carlosdomenje/bdd_tp3_cdomenje#3]
Lo que se agrega en este paso no es un solo elemento, debería decir cuando se agregan los siguientes elementos.

https://github.com/carlosdomenje/bdd_tp3_cdomenje/blob/52d0100ec8e20703bf83043bfb76da0abac1e709/features/gestion.feature#L43-L48

**Comment by carlosdomenje** [comment]
> Lo que se agrega en este paso no es un solo elemento, debería decir cuando se agregan los siguientes elementos.
> 
> https://github.com/carlosdomenje/bdd_tp3_cdomenje/blob/52d0100ec8e20703bf83043bfb76da0abac1e709/features/gestion.feature#L43-L48

Se modificaron varios errores de redaccion ademas de este.
