### ISSUE TITLE
No se aplicó correctamente la metodología

### ISSUE THREAD

**Issue by evolentini** [carlosdomenje/bdd_tp3_cdomenje#4]
Esta función no es necesaria para cumplir ninguno de los requisitos dados, eso quiere decir que o bien no se definieron correctamente las pruebas en función de los requisitos o que no se aplicó correctamente la metodología para escribir el código mínimo y necesario en cada paso.

https://github.com/carlosdomenje/bdd_tp3_cdomenje/blob/52d0100ec8e20703bf83043bfb76da0abac1e709/src/lista.js#L24-L31

**Comment by carlosdomenje** [comment]
> Esta función no es necesaria para cumplir ninguno de los requisitos dados, eso quiere decir que o bien no se definieron correctamente las pruebas en función de los requisitos o que no se aplicó correctamente la metodología para escribir el código mínimo y necesario en cada paso.
> 
> https://github.com/carlosdomenje/bdd_tp3_cdomenje/blob/52d0100ec8e20703bf83043bfb76da0abac1e709/src/lista.js#L24-L31

Se resuelve con la funcion count(), no es necesaria la funcion find(), por lo que fue eliminada y reemplazada.
